# Generated by Django 5.1.2 on 2024-10-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("published", "Published"),
                    ("cancelled", "Cancelled"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
