name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DJANGO_PG_NAME: note_db
  DJANGO_PG_USER: note_user
  DJANGO_PG_PASSWORD: note_password
  DJANGO_PG_HOST: 127.0.0.1
  DJANGO_PG_PORT: 5432

  DJANGO_REDIS_CACHE: redis://127.0.0.1:6379/0
  CELERY_BROKER_URL: redis://127.0.0.1:6379/1
  CELERY_RESULT_BACKEND: redis://127.0.0.1:6379/2

jobs:
  test:

    services:
      cache:
        image: redis:latest
        ports:
          - "6379:6379"

      database:
        image: postgres:17.2-alpine
        env:
          POSTGRES_USER: ${{env.DJANGO_PG_USER}}
          POSTGRES_PASSWORD: ${{env.DJANGO_PG_PASSWORD}}
          POSTGRES_DB: ${{env.DJANGO_PG_NAME}}
        ports:
          - "${{env.DJANGO_PG_PORT}}:5432"

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: python manage.py test

  build_docker:
    needs:
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE_NAME }}:latest
